In [1]:
import numpy as np
l1=[1,2,3,4,5,6,7,8,9]
#print(l1)

l2=[11,12,13,14,15,16,17,18]
#print(l2)

l3=[l1,l2]
#print(l3)

v1=np.array(l1)
print(v1+5)
print(v1*2)
print(v1[1:5])
print(v1[::-1])
print(v1[0:5:-1])


print("now for 2d array")

s=[[1,2,3],[3,4,5],[5,6,7]]

s1=np.array(s)
print(s1[1])
print(s1[2])
print(s1[-1])
print(s1[1][1])
print(s1[1][-1])
print(s1[-1][-2])
print(s1[1][0])
s1[0][0]=12
s2=(s1+s1)
print(s2)
print([s1],[s1])

[ 6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14 16 18]
[2 3 4 5]
[9 8 7 6 5 4 3 2 1]
[]
now for 2d array
[3 4 5]
[5 6 7]
[5 6 7]
4
5
6
3
[[24  4  6]
 [ 6  8 10]
 [10 12 14]]
[array([[12,  2,  3],
       [ 3,  4,  5],
       [ 5,  6,  7]])] [array([[12,  2,  3],
       [ 3,  4,  5],
       [ 5,  6,  7]])]
